version: 2
builds:
  - binary: awsctl
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

release:
  prerelease: auto

universal_binaries:
  replace: true

checksum:
  name_template: 'checksums.txt'