version: 2
builds:
  - binary: awsctl
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  - name: awsctl
    homepage: https://github.com/prastamaha/awsctl
    repository:
      owner: prastamaha
      name: homebrew-tap
    commit_author:
      name: prasamaha
      email: prastamaha@gmail.com

checksum:
  name_template: 'checksums.txt'